/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Pools Endpoint
         * @description List all available voice pools.
         */
        get: operations["list_pools_endpoint_voices_pools_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices/pools/{poolName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pool Endpoint
         * @description Get all voices in a pool.
         */
        get: operations["get_pool_endpoint_voices_pools__poolName__get"];
        /**
         * Update Pool Endpoint
         * @description Update an existing pool.
         */
        put: operations["update_pool_endpoint_voices_pools__poolName__put"];
        /**
         * Create Pool Endpoint
         * @description Create a new pool.
         */
        post: operations["create_pool_endpoint_voices_pools__poolName__post"];
        /**
         * Delete Pool Endpoint
         * @description Delete a pool.
         */
        delete: operations["delete_pool_endpoint_voices_pools__poolName__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Voices
         * @description List all available voices, optionally filtered by pool.
         *
         *     Args:
         *         pool: Optional pool name to filter voices
         */
        get: operations["list_voices_voices_get"];
        put?: never;
        /**
         * Create Voice Endpoint
         * @description Create a new voice using voice design (Qwen only).
         *
         *     Generates voice from text description. Not supported for VibeVoice backend.
         *     For VibeVoice, use POST /voices/clone instead.
         *
         *     Generates WAV and prompt files and saves the voice to the database.
         *     Returns a job ID to track generation progress.
         */
        post: operations["create_voice_endpoint_voices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices/{voiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Voice Endpoint
         * @description Get voice details by ID.
         */
        get: operations["get_voice_endpoint_voices__voiceId__get"];
        /**
         * Update Voice Endpoint
         * @description Update an existing voice configuration.
         *
         *     If config changed, triggers regeneration job.
         *     Otherwise, just saves the updated configuration.
         */
        put: operations["update_voice_endpoint_voices__voiceId__put"];
        post?: never;
        /**
         * Delete Voice Endpoint
         * @description Delete a voice.
         *
         *     Removes the voice from the database and all pools.
         *     Does not delete WAV or prompt files.
         */
        delete: operations["delete_voice_endpoint_voices__voiceId__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voices/clone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clone Voice Endpoint
         * @description Create a new voice using voice cloning from reference audio.
         *
         *     Works with all backends (qwen, vibevoice). Requires reference audio file.
         *     Generates a prompt from the reference audio and saves the voice to the database.
         *     Returns a job ID to track generation progress.
         */
        post: operations["clone_voice_endpoint_voices_clone_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Stories Endpoint
         * @description List all stories.
         *
         *     Returns story summaries with id, slug, and title.
         */
        get: operations["list_stories_endpoint_stories_get"];
        put?: never;
        /**
         * Create Story Endpoint
         * @description Create a new story template.
         *
         *     Voice assignment: Use the `casting` field to map roleIds (as strings) to voiceIds.
         *     Resolution order: line.actorId → casting[roleId] → defaultVoiceId
         *
         *     Example casting: {"0": "narrator_male", "1": "woman"} assigns roleId 0 to narrator_male, roleId 1 to woman.
         *
         *     Returns the story with server-generated `id` (UUID) and `slug` fields.
         */
        post: operations["create_story_endpoint_stories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Endpoint
         * @description Get story template by ID or slug.
         *
         *     The identifier can be either:
         *     - A UUID (e.g., "550e8400-e29b-41d4-a716-446655440000")
         *     - A slug (e.g., "my_story_title")
         */
        get: operations["get_story_endpoint_stories__identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace Story Endpoint
         * @description Replace an existing story template.
         */
        put: operations["replace_story_endpoint_stories__storyId__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Story Endpoint
         * @description Resolve roles to voices for a story.
         *
         *     Returns a preview of voice assignments showing which voice will be used for each line.
         *     Resolution order: line.actorId → casting[roleId] → defaultVoiceId
         *
         *     Use this endpoint to verify voice assignments before generating audio.
         */
        post: operations["render_story_endpoint_stories__storyId__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stories/{storyId}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Story Endpoint
         * @description Start audio generation for a story.
         *
         *     Only one job per story can be running or queued at a time.
         *     If a job is already active for this story, returns 409 Conflict unless
         *     cancel_existing=true, in which case the active job is cancelled and a new one is started.
         */
        post: operations["generate_story_endpoint_stories__storyId__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs Endpoint
         * @description List active (queued/running) jobs. Use the Jobs UI to cancel if needed.
         */
        get: operations["list_jobs_endpoint_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Endpoint
         * @description Get job status by ID.
         */
        get: operations["get_job_endpoint_jobs__jobId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job Endpoint
         * @description Cancel an active (queued or running) job.
         *     Marks the job as failed with message 'Cancelled by user'.
         *     Returns 404 if job not found, 409 if job is not active (already finished).
         */
        post: operations["cancel_job_endpoint_jobs__jobId__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Reference Audio
         * @description Upload a WAV reference clip for voice cloning.
         *
         *     The file is stored under `uploads/reference_audio/` with a sanitized unique
         *     name. Use the returned `file_path` as `ref_audio_url` when cloning a voice.
         */
        post: operations["upload_reference_audio_audio_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/voices/{voiceId}.wav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Voice Audio
         * @description Download the backend-specific reference/sample audio for a voice.
         */
        get: operations["get_voice_audio_audio_voices__voiceId__wav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/stories/{storyId}/full.wav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Audio
         * @description Download the concatenated audio file for a story.
         */
        get: operations["get_story_audio_audio_stories__storyId__full_wav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/stories/{storyId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Story Audio Files
         * @description List all individual audio files for a story.
         */
        get: operations["list_story_audio_files_audio_stories__storyId__files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audio/stories/{storyId}/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Story Audio File
         * @description Download a specific individual audio file for a story.
         */
        get: operations["get_story_audio_file_audio_stories__storyId__files__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_reference_audio_audio_upload_post */
        Body_upload_reference_audio_audio_upload_post: {
            /** File */
            file: string;
        };
        /**
         * GenerateRequest
         * @description Request body for story generation.
         */
        GenerateRequest: {
            /**
             * Concat
             * @description Whether to concatenate outputs
             * @default true
             */
            concat: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description A generation job.
         */
        Job: {
            /**
             * Id
             * @description Job identifier
             */
            id: string;
            /**
             * Type
             * @description Job type (e.g., 'generate', 'voice_generate')
             */
            type: string;
            /**
             * Status
             * @description Job status: queued, running, succeeded, failed
             */
            status: string;
            /**
             * Storyid
             * @description Associated story ID
             */
            storyId?: string | null;
            /**
             * Voiceid
             * @description Associated voice ID
             */
            voiceId?: string | null;
            /**
             * Message
             * @description Status message or error
             */
            message?: string | null;
            /**
             * Outputpath
             * @description Path to generated audio file
             */
            outputPath?: string | null;
            /**
             * Createdat
             * @description Job creation timestamp (ISO 8601)
             */
            createdAt: string;
            /**
             * Startedat
             * @description Job start timestamp (ISO 8601)
             */
            startedAt?: string | null;
            /**
             * Finishedat
             * @description Job completion timestamp (ISO 8601)
             */
            finishedAt?: string | null;
            /**
             * Requestparams
             * @description Request parameters for generation
             */
            requestParams?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ResolvedLine
         * @description A story line with resolved voice assignment.
         *
         *     This is the result of resolving a StoryLine using the resolution order:
         *     actorId → casting[roleId] → defaultVoiceId
         */
        ResolvedLine: {
            /**
             * Id
             * @description Line identifier
             */
            id: number;
            /**
             * Roleid
             * @description Role identifier
             */
            roleId: number;
            /**
             * Voiceid
             * @description Resolved voice ID that will be used for this line
             */
            voiceId: string;
            /**
             * Line
             * @description The text to speak
             */
            line: string;
            /**
             * Extra
             * @description Performance hint
             */
            extra?: string | null;
        };
        /**
         * Role
         * @description A role in a story.
         */
        Role: {
            /**
             * Roleid
             * @description Unique role identifier
             */
            roleId: number;
            /**
             * Name
             * @description Role name
             */
            name: string;
            /**
             * Notes
             * @description Optional author notes
             */
            notes?: string | null;
        };
        /**
         * StoryLine
         * @description A single line in a story.
         */
        StoryLine: {
            /**
             * Id
             * @description Unique line identifier
             */
            id: number;
            /**
             * Roleid
             * @description Role that speaks this line
             */
            roleId: number;
            /**
             * Line
             * @description The text to speak
             */
            line: string;
            /**
             * Extra
             * @description Performance hint (e.g., 'curious, excited')
             */
            extra?: string | null;
            /**
             * Actorid
             * @description Optional per-line voice override. Highest priority in voice resolution: actorId → casting[roleId] → defaultVoiceId
             */
            actorId?: string | null;
        };
        /**
         * StorySummary
         * @description Summary of a story for list endpoints.
         */
        StorySummary: {
            /**
             * Id
             * @description Unique story identifier (UUID)
             */
            id?: string | null;
            /**
             * Slug
             * @description URL-friendly identifier
             */
            slug: string;
            /**
             * Title
             * @description Story title
             */
            title: string;
        };
        /**
         * StoryTemplate
         * @description A story template with roles and lines.
         *
         *     Voice assignment resolution order (for each line):
         *     1. line.actorId (if present) - per-line override
         *     2. casting[str(roleId)] (if present) - role-level assignment
         *     3. defaultVoiceId - fallback for all unassigned roles
         *
         *     Example casting: {"0": "narrator_male", "1": "woman"} maps roleId 0 to narrator_male, roleId 1 to woman.
         */
        StoryTemplate: {
            /**
             * Id
             * @description Unique story identifier (UUID). Set by server on creation.
             */
            id?: string | null;
            /**
             * Slug
             * @description URL-friendly identifier derived from title. Set by server on creation.
             */
            slug?: string | null;
            /**
             * Schemaversion
             * @description Schema version
             * @default 1
             * @constant
             */
            schemaVersion: 1;
            /**
             * Title
             * @description Story title
             */
            title: string;
            /**
             * Language
             * @description Language for TTS generation (e.g., 'English', 'Chinese', 'Spanish')
             * @default English
             */
            language: string;
            /**
             * Defaultvoiceid
             * @description Fallback voice ID used when a role has no casting assignment and line has no actorId
             */
            defaultVoiceId: string;
            /**
             * Roles
             * @description Story roles
             */
            roles: components["schemas"]["Role"][];
            /**
             * Casting
             * @description Optional map of roleId (as string key) to voiceId (string value). Example: {'0': 'narrator_male', '1': 'woman'}. Keys must be string representations of roleId integers.
             * @example {
             *       "0": "narrator_male",
             *       "1": "woman",
             *       "2": "child"
             *     }
             */
            casting?: {
                [key: string]: string;
            } | null;
            /**
             * Lines
             * @description Story lines
             */
            lines: components["schemas"]["StoryLine"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Voice
         * @description A voice definition.
         */
        Voice: {
            /** Id */
            id: string;
            /**
             * Language
             * @description Language for this voice
             */
            language: string;
            /**
             * Instruction
             * @description Voice instruction/prompt
             */
            instruction: string;
            /**
             * Sample Text
             * @description Sample text for this voice
             */
            sample_text?: string | null;
            /**
             * Backend
             * @description TTS backend (qwen, vibevoice)
             * @default qwen
             */
            backend: string;
            /**
             * Promptpath
             * @description Path to prompt file
             */
            promptPath?: string | null;
            /**
             * Refaudiopath
             * @description Path to reference audio
             */
            refAudioPath?: string | null;
        };
        /**
         * VoiceCloneConfig
         * @description Voice configuration for voice cloning from reference audio (works with all backends).
         *
         *     Workflow:
         *     1. Upload reference audio: POST /audio/upload (returns file_path)
         *     2. Use file_path in ref_audio_url field
         *     3. Create voice clone: POST /voices/clone
         */
        VoiceCloneConfig: {
            /**
             * Id
             * @description Voice identifier
             */
            id: string;
            /**
             * Language
             * @description Language for this voice
             */
            language: string;
            /**
             * Instruction
             * @description Voice description/notes
             */
            instruction: string;
            /**
             * Ref Audio Url
             * @description Path to reference audio file (WAV format). Upload via POST /audio/upload first to get the path.
             */
            ref_audio_url: string;
            /**
             * Ref Text
             * @description Optional transcript of reference audio
             */
            ref_text?: string | null;
            /**
             * Backend
             * @description TTS backend to use (qwen, vibevoice)
             * @default qwen
             */
            backend: string;
        };
        /**
         * VoiceConfig
         * @description Voice configuration for creation/update using voice design (Qwen only).
         */
        VoiceConfig: {
            /**
             * Id
             * @description Voice identifier
             */
            id: string;
            /**
             * Language
             * @description Language for this voice
             */
            language: string;
            /**
             * Instruction
             * @description Voice instruction/prompt
             */
            instruction: string;
            /**
             * Sample Text
             * @description Sample text for voice generation
             */
            sample_text: string;
            /**
             * Backend
             * @description TTS backend to use (qwen only - vibevoice not supported for voice design)
             * @default qwen
             */
            backend: string;
        };
        /**
         * VoicePool
         * @description A pool of voices grouped by theme.
         */
        VoicePool: {
            /**
             * Name
             * @description Pool name
             */
            name: string;
            /**
             * Voiceids
             * @description List of voice IDs in this pool
             */
            voiceIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_pools_endpoint_voices_pools_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_pool_endpoint_voices_pools__poolName__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poolName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_pool_endpoint_voices_pools__poolName__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poolName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoicePool"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePool"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pool_endpoint_voices_pools__poolName__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poolName: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoicePool"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoicePool"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pool_endpoint_voices_pools__poolName__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                poolName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_voices_voices_get: {
        parameters: {
            query?: {
                pool?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_voice_endpoint_voices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice_endpoint_voices__voiceId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Voice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_voice_endpoint_voices__voiceId__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_voice_endpoint_voices__voiceId__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clone_voice_endpoint_voices_clone_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceCloneConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stories_endpoint_stories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorySummary"][];
                };
            };
        };
    };
    create_story_endpoint_stories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryTemplate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_endpoint_stories__identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_story_endpoint_stories__storyId__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryTemplate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryTemplate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_story_endpoint_stories__storyId__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedLine"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_story_endpoint_stories__storyId__generate_post: {
        parameters: {
            query?: {
                cancel_existing?: boolean;
            };
            header?: never;
            path: {
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_endpoint_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
        };
    };
    get_job_endpoint_jobs__jobId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_endpoint_jobs__jobId__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_reference_audio_audio_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_reference_audio_audio_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_voice_audio_audio_voices__voiceId__wav_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voiceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_audio_audio_stories__storyId__full_wav_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_story_audio_files_audio_stories__storyId__files_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_story_audio_file_audio_stories__storyId__files__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
                storyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
